database/migrations/2023_08_23_210836_make_incident_components_table_status_id_column_null.php
tests/Unit/Models/IncidentTest.php

in this PR i have noticied the **Component** model and **ComponentStatusEnum**
also i have noticed the migration change in the incidents table... which made me think that this change maybe introduced for backward compatibility when upgrading from older version of cachet
so based on the above I have modified the **status_id** column on **incident_components** and made it null
hopefully am right about my thoughts 😂

Fix incident components relation

---

canvas.yaml
composer.json

This allows us to run `composer canvas` followed by any of the `artisan` supported make commands, which makes developing this package even easier.
For example, running:
```
composer canvas make:middleware Dashboard
```
Will stub a file to `./src/Http/Middleware/Dashboard.php` 🎉

Add Orchestra Canvas config

---

tests/TestCase.php

`WithWorkbench` + `RefreshDatabase` combined with `testbench.yaml` configuration below should already load default migrations and run migrations from `workbench/database/migrations`:
```yaml
migrations:
- workbench/database/migrations
workbench:
install: true
```

Test Improvements

---

src/CachetCoreServiceProvider.php

This replaces the need for the previous [`cachet:version`](https://github.com/cachethq/cachet/blob/2323e9c0e36100f561ba03f029d87e2543636e81/app/Console/Commands/VersionCommand.php) command that we had.

Add Cachet section to `about` command

---

src/Models/MetricPoint.php
tests/Unit/Actions/Metric/CreateMetricPointTest.php

We do this [currently](https://github.com/cachethq/cachet/blob/2323e9c0e36100f561ba03f029d87e2543636e81/app/Models/MetricPoint.php#L110-L128), and although I cannot remember _why_ we do it, I figured it's best to continue doing so. I _think_ it's so we can more easily group the points for the charts.

Round metric point timestamp into 30 second intervals

---

database/factories/ComponentFactory.php
database/factories/IncidentUpdateFactory.php
src/Http/Controllers/Api/IncidentController.php
src/Http/Controllers/Api/MetricController.php
tests/Feature/Api/ComponentGroupTest.php
tests/Feature/Api/ComponentTest.php
tests/Feature/Api/IncidentTest.php
tests/Feature/Api/IncidentUpdateTest.php
tests/Feature/Api/MetricPointTest.php
tests/Feature/Api/MetricTest.php
tests/Feature/Api/ScheduleTest.php
tests/TestCase.php

This PR updates `MetricController::index()` and `IncidentController::index()` to default the ordering of results by the `created_at` date in descending order.
Tests have been included to check this is the case, and to check the default sorting, the ability to sort and the ability to filter various resources.
Resolves #10

API Sorts and Filters

---

routes/api.php

This PR simplifies the registration of API routes, by combining related registration declarations into a single `apiResource` declaration.
Most resources can be bundled together via `Route::apiResources([...])`. However, the scoped resources `incidents.updates` and `metrics.points` have to be registered as separate `Route::apiResource(...)` to accommodate correctly scoping resources to their parents as well as defining the route param names used by Laravel's implicit route binding (thus removing the requirement to alter the variable names type hinted in the controllers... e.g. renaming `$incidentUpdate` to just `$update`)

Simplify API Route Registration

---

config/cachet.php
src/CachetCoreServiceProvider.php
src/CachetServiceProvider.php
tests/Feature/RateLimitTest.php
tests/TestCase.php

closes #35 
Adds a default rating limit of 300 requests / minute to all cachet API routes, overridable via the `cachet.api_rate_limit` config setting.

API Rate Limiting

---

config/cachet.php
src/Jobs/SendBeaconJob.php
tests/Unit/Jobs/SendBeaconJobTest.php

This PR brings back the Beacon, which sends optional and anonymous telemetry data to cachethq.io
> [!Note]
> In Cachet 2.x we would include the contact email, but we've dropped this now.

Beacon Telemetry

---

config/cachet.php
src/Cachet.php

Hey,
When clicking around the application I noticed that the `Status Page` in the navigation menu was resolving to the relative path:-
```
http://127.0.0.1:8000/status/status
```
So I've updated the defaults to contain the prefixed forward slash.

Prefix the default cachet path with slash

---

src/Enums/ScheduleStatusEnum.php
src/Filament/Resources/ScheduleResource.php
src/Filament/Resources/ScheduleResource/Pages/EditSchedule.php

**Issue:** https://github.com/cachethq/core/issues/75
Hopefully this is ok, I'm changing the completed_at timestamp to null when the status is changed to any status which isn't completed. We have to also do this in `mutateFormDataBeforeSave` method before saving as well as because the input is not visible it doesn't post the data and therefore preserves the original value.
The reason I had to add the enum method is sourced from a very similar issue here: https://github.com/filamentphp/filament/issues/10206
The Filament resource was returning inconsistent types, on create it was returning the enum type but on edit the values were being returned as integers.

Support change of completed at date and clear when status is changed.

---

resources/lang/en.json
resources/views/components/incident-timeline.blade.php
resources/views/components/incident.blade.php
resources/views/components/schedule.blade.php

Dates and timestamps in the incident timeline and schedule list are now localized based on the user's browser. In the screenshot below I'm using EN-US as my browser locale, so we've formatted per US rules.
This will make up part of #65.

Incident Timeline and Schedule Localization

---

resources/lang/en.json
resources/views/components/incident.blade.php
resources/views/status-page/incident.blade.php
src/Filament/Resources/IncidentResource.php
src/Models/Incident.php

Hey @jbrooksuk! This PR is an attempt to add some features mentioned in #73. I'm still really new to Cachet and Filament, so I do apologise if I've completely misunderstood what's needed and done it wrong. If that's the case, gimme a shout, and I'll get this PR updated right away 😄
This PR proposes that the UUID is now available in the Filament dashboard (at the bottom of the right hand panel):
It also adds the incident UUID to the incidents on the public-facing pages (in the bottom right of the incident cards):
And if the user is authenticated, then a "View in Dashboard" link will be displayed that takes the user directly to the "edit" page in the Filament dashboard. This link is in the bottom right of the incident card again:
I've not committed my `manifest.json` and …

Make the UUID visible for incidents

---

resources/views/components/component-ungrouped.blade.php
resources/views/status-page/index.blade.php
src/Http/Controllers/StatusPage/StatusPageController.php

Instead of grouping ungrouped components into an "Ungrouped Components" group, let's just list them separately, as intended. If you want them grouped, create a group :)

Separate ungrouped components on the status page

---

src/Filament/Widgets/Components.php
tests/Feature/Filament/Widgets/ComponentsTest.php

Currently, both grouped components and component groups can be reordered in their Filament resources, but these changes are not reflected on the dashboard. This PR resolves the issue.

Fix Component Order on Dashboard

---

resources/views/components/incident.blade.php

This PR improves the empty state view by adding some styling and aligning the sections.
- Desktop:
- Mobile:
Closes #94

Improves the empty state view

---

src/Filament/Resources/ComponentGroupResource.php
src/Filament/Resources/ComponentResource.php
src/Filament/Resources/IncidentResource.php
src/Filament/Resources/IncidentTemplateResource.php
src/Filament/Resources/MetricResource.php
src/Filament/Resources/ScheduleResource.php
src/Filament/Resources/SubscriberResource.php

Laravel by default forms plurals by appending an “s”, but this does not work in all languages (such as German).
This PR explicitly adds the plural forms in order to be able to translate them independently.

feat: translate plurals independently

---

README.md
composer.json

Laravel 11.x has introduced a new `composer dev` command to get up and running quickly. I've added this to our `composer.json` file and aliased `composer start` to it 🚀 
We also now install `laravel/pail` as a dev dependency and start queues, so it's even easier to build features such as #22 and #79.

Composer Dev Command

---

database/factories/ScheduleFactory.php
database/migrations/2024_10_13_214300_drop_schedule_status.php
database/seeders/DatabaseSeeder.php
src/Filament/Resources/ScheduleResource.php
src/Http/Controllers/Api/ScheduleController.php
src/Http/Controllers/StatusPage/StatusPageController.php
src/Http/Resources/Schedule.php
src/Models/Schedule.php
tests/Feature/Api/ScheduleTest.php
tests/Unit/Actions/Schedule/CreateScheduleTest.php
tests/Unit/Models/ScheduleTest.php

feat: Time-controlled status for Planned Maintenances / Schedules

---

composer.json
database/factories/ScheduleComponentFactory.php
src/Http/Controllers/Api/ComponentController.php
src/Http/Controllers/Api/ComponentGroupController.php
src/Http/Controllers/Api/GeneralController.php
src/Http/Controllers/Api/IncidentController.php
src/Http/Controllers/Api/IncidentTemplateController.php
src/Http/Controllers/Api/IncidentUpdateController.php
src/Http/Controllers/Api/MetricController.php
src/Http/Controllers/Api/MetricPointController.php
src/Http/Controllers/Api/ScheduleController.php
src/Http/Controllers/Api/StatusController.php
src/Models/Component.php
src/Models/ComponentGroup.php
src/Models/Incident.php
src/Models/IncidentComponent.php
src/Models/IncidentTemplate.php
src/Models/IncidentUpdate.php
src/Models/Metric.php
src/Models/MetricPoint.php
src/Models/Schedule.php
src/Models/ScheduleComponent.php
src/Models/Subscriber.php
src/Models/Subscription.php

This PR annotates the API controllers in a way that we can use [Scribe](https://scribe.knuckles.wtf) to generate the API documentation.
1. I'm currently using Scribe within the `cachethq/cachet` application itself to generate the documentation. For this to work, I've had to override each model's `newFactory` method to return the correct class.
2. I've updated all endpoint docblocks to use Scribe's PHP annotations (we can't use the attribute syntax, since Scribe isn't in the core itself).
At some point, I'm going to automate all of this in the main repo itself.

Scribe Annotations

---

src/Concerns/HasVisibility.php
src/Models/Component.php
src/Models/Incident.php
src/Models/Schedule.php

I forget this, but local scopes can either return the same builder instance **or** `void`. I'm settling on returning `void`.
https://laravel.com/docs/11.x/eloquent#local-scopes

Local scopes can return `void`

---

README.md

Reverts cachethq/core#148
These changes don’t work for me in Safari iOS.

Revert "Changing cachet media color dark to light"

---

src/Models/Schedule.php
tests/Unit/Models/ScheduleTest.php

Fixes an issue detected by running the tests at midnight 😅 See [schedule test-run](https://github.com/cachethq/core/actions/runs/12449503451).
I added an additional test to check what happens around midnight, which is when this issue was noticed.

Fix bug determining incomplete schedules

---

database/factories/IncidentComponentFactory.php
database/migrations/2024_12_24_120457_rename_incident_components_status.php
src/Filament/Resources/IncidentResource/RelationManagers/ComponentsRelationManager.php
src/Models/Component.php
src/Models/Incident.php
src/Models/IncidentComponent.php
tests/Unit/Models/ComponentTest.php
tests/Unit/Models/IncidentTest.php

Due to the `status` column clashing with incidents themselves, we were always showing the incident's status for attached components.
This PR renames `incident_components.status` to `incident_components.component_status`.

Fix attaching components to incidents

---

config/cachet.php

Since Cachet should ideally be installed at the root of a Laravel application, let's make this the default. 
On my phone, so probably going to have tests to fix first. 
Fixes https://github.com/cachethq/cachet/issues/4446

Set default path to root

---

src/CachetCoreServiceProvider.php

This job needs to be registered in the scheduler so that it works automatically.

Register the `cachet:beacon` command as a scheduled job

---

resources/views/components/incident.blade.php

removing `ml-9` fixed the problem.

Fix #167: Make 'no incidents reported' full width

---

src/Filament/Pages/Settings/ManageTheme.php

The alignment of the swatch icon to the text was bugging me. This PR centres them vertically.
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/fcbbb1d9-de8d-411a-ab76-974e4fd75b3d) | ![image](https://github.com/user-attachments/assets/e0e47dc9-a0c6-4dca-8f26-69e84ad93178) |

fix: alignment of swatch icon

---

database/migrations/2023_08_23_210836_make_incident_components_table_status_id_column_null.php

When running this migration with php8.3, postgresql 15 and latest version of all components, I get the following migration error:
```
2023_08_23_210836_make_incident_components_table_status_id_column_null .............................. 1.84ms FAIL
Illuminate\Database\QueryException 
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "status_id" of relation "incident_components" does not exist (Connection: pgsql, SQL: comment on column "incident_components"."status_id" is NULL)
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
822▕                 );debug2: channel 0: window 999401 sent adjust 49175
823▕             }
824▕ 
➜ 825▕             throw new QueryException(
826▕ …
```

fix migration with postgresql

---

testbench.yaml

Sets the `AUTH_MODEL` env variable for workbench so that it uses the `Workbench\App\User` model instead of the workbench default (`Illuminate\Foundation\Auth\User`)

Set workbench auth model

---

database/migrations/2025_01_15_121008_add_admin_flag_to_users_table.php
resources/lang/en/user.php
src/Commands/MakeUserCommand.php
src/Filament/Resources/UserResource.php

Allows admin users to be created for cachet.
- Adds an `is_admin` flag to the `users` table
- Adds a toggle to the create user form
- Adds a toggle to the users table
- Updates the `cachet:make:user` command

Create Admin users

---

src/Http/Controllers/Api/ComponentController.php
src/Http/Controllers/Api/IncidentController.php
src/Http/Controllers/Api/IncidentUpdateController.php
src/Http/Controllers/Api/ScheduleController.php
src/Http/Resources/Component.php
src/Http/Resources/Incident.php

This PR:
- Uses `AllowedFilter::exact()` filters for `status` and `enabled` filters for components, incidents, incident updates and schedules -  this fixes a bug when applying the filter errors if using Postgres
- Fixes `status` in the component resource to now have a human readable value (like the rest)

Applies various fixes to API endoints

---

config/cachet.php
database/migrations/2025_01_16_225001_add_locale_to_user.php
resources/lang/en/user.php
src/CachetDashboardServiceProvider.php
src/Filament/Resources/UserResource.php
src/Http/Middleware/SetAppLocale.php
src/Models/User.php

This PR allows selecting the preferred locale for a user.
It also adds a middleware that sets the application locale to the user's preferred locale, or the system default (as specified by the browser in the `Accept-Language` header) if one isn't set.
I've specified the supported locales in the config file, and this will be used for:
- The options which a user can pick from
- Which locale to use when the browser sends multiple locale preferences
Changing the locale changes the language the user sees and the way in which dates and numbers are formatted in.
The application uses the fallback locale if a string doesn't have a translation defined for the given locale.
Going forward, if any new translation strings are added, the locale code should be added to the `supported_locales` config file. …

feat: Add ability to pick preferred locale for a user

---

src/Filament/Resources/IncidentResource.php

`latest_status` will display either the incident's status or the latest incident update's status.
Fixes #195

Display latest_status in Incident table

---

src/Filament/Resources/ComponentGroupResource.php
src/Filament/Resources/ComponentResource.php

Fixes https://github.com/cachethq/core/issues/202
I've also made sure that the Component and Component Group resources are default sorted by the `order` column, so switching to order mode remains in the same order.

Make Component Group sortable in dashboard

---

src/Filament/Resources/IncidentTemplateResource.php

Rather than debouncing, let's just generate the slug when the name blurs.

Generate incident template slug on blur from name field

---

config/cachet.php
src/Cachet.php
src/Http/Middleware/AuthenticateRemoteUser.php
tests/Feature/Http/Middleware/AuthenticateRemoteUserTest.php

Copied from v2.4 based on some feedback I received.
We should also implement something more modern like SAML.

Support the `HTTP_REMOTE_USER` header

---

config/cachet.php
resources/lang/ph/api_key.php
resources/lang/ph/cachet.php
resources/lang/ph/component.php
resources/lang/ph/component_group.php
resources/lang/ph/incident.php
resources/lang/ph/incident_template.php
resources/lang/ph/integrations.php
resources/lang/ph/metric.php
resources/lang/ph/navigation.php
resources/lang/ph/resource.php
resources/lang/ph/schedule.php
resources/lang/ph/settings.php
resources/lang/ph/subscriber.php
resources/lang/ph/system_status.php
resources/lang/ph/user.php
resources/lang/ph/webhook.php

@jbrooksuk, can you check if the one I did is correct? Just let me know if there's anything wrong so I can edit it as quickly as possible. I kept some words in English because it's easier to understand the technology terms rather than translating them to Filipino, but the words I kept are only minimal.

Updated PH localization

---

src/Commands/MakeUserCommand.php

When trying to create a user with the `--no-interaction` flag the following error occurs
```
php artisan cachet:make:user test@test.com --password="password" --admin --no-interaction
Laravel\Prompts\Exceptions\NonInteractiveValidationException
Required.
at vendor/laravel/prompts/src/Concerns/Interactivity.php:32
28▕
29▕         $this->validate($default);
30▕
31▕         if ($this->state === 'error') {
➜  32▕             throw new NonInteractiveValidationException($this->error);
33▕         }
34▕
35▕         return $default;
36▕     }
+17 vendor frames
18  artisan:13
Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```
There is currently no `--name` flag available
```
php artisan cachet:make:user test@test.com --password="password" --admin …
```

fix: make user command does not accept a name argument

---

src/Data/BaseData.php
workbench/config/data.php

This PR adds a snake case name mapper PHP attribute to `BaseData`.
closes #225 
As discovered in #225, the API tests are returning a false positive, because of the [Laravel Data configuration used for testbench](https://github.com/cachethq/core/blob/efcdc1ee2127f43805eec3bf1964cb8bdf633624/workbench/config/data.php#L134-L137):
```php
'name_mapping_strategy' => [
'input' => \Spatie\LaravelData\Mappers\SnakeCaseMapper::class,
'output' => \Spatie\LaravelData\Mappers\SnakeCaseMapper::class,
],
```
Setting both of these values to `NULL` and running the test suite highlights the error. Of course, this is fine in our tests as we are specifying the Laravel app to uses these mappers. However applications consuming this package might not have Laravel Data configured this way.
Since we have …

[fix] name mapping in request data classes

---

src/Commands/MakeUserCommand.php

Neglected to remove this prompt to account for non-interactive mode in my prior PR https://github.com/cachethq/core/pull/216 
@jbrooksuk do you mind reviewing this again?

fix: remove additional prompt for name

---

resources/lang/nl/component.php
resources/lang/nl/incident.php
resources/lang/nl/metric.php
resources/lang/nl/schedule.php
src/Commands/MakeUserCommand.php

The Dutch translation has been adjusted so that the text aligns better with what is intended.

Fix dutch translations

---

src/Http/Controllers/Auth/VerifyEmailController.php
src/Models/User.php
src/PendingRouteRegistration.php
tests/Feature/Http/Controllers/Auth/EmailVerificationTest.php
workbench/database/factories/UserFactory.php

[3.x] Add email verification route

---

src/Status.php

Fix the following issue with postgresql:
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "" CONTEXT: unnamed portal parameter $2 = '' (Connection: pgsql, SQL: select count(*) as total, sum(case when 4 in (incidents.status, coalesce(latest_update.status, )) then 1 else 0 end) as resolved, sum(case when 4 not in (incidents.status, coalesce(latest_update.status, )) then 1 else 0 end) as unresolved from "incidents" left join (select "iu1"."updateable_id", "iu1"."status" from "updates" as "iu1" left join (select "updateable_id", max(id) as max_id from "updates" where "updates"."updateable_type" = incident group by "updateable_id") as "iu2" on "iu1"."id" = "iu2"."max_id") as "latest_update" on "latest_update"."updateable_id" = "incidents"."id" …
```

Fix issue with postgresql

---

database/migrations/2025_03_02_172736_add_default_to_preferred_locale_column_in_users_table.php

This PR resolves #249 
When a user registers first, by default in the `users` table `preferred_locale` is set as `NULL`. Therefore if we set `default()` in `select form component` it would not work unless the user clicks the `save changes` button. The same result if we change in config.
Therefore, according to my perspective, to set English as the default language, we should do it when creating a user at the database level. That's why I added this migration.

fix(locale): Added a migration to set user preferred locale value

---

resources/views/status-page/index.blade.php
src/Http/Controllers/StatusPage/StatusPageController.php
src/Settings/AppSettings.php

The "Display Graphs" option wasn't correctly wired up and the setting had no bearing on whether graphs were displayed or not.

Optionally display the metric graphs

---

src/Commands/MakeUserCommand.php
tests/Unit/Commands/MakeUserCommandTest.php

This is based off a recent conversation in Discord - frank42 mentioned that a user is being created as a non-admin even when they said "Yes" to the admin prompt.
I can't replicate that particular bug, but I thought it'd be good to have some tests on this command anyway.
This also fixes a bug where if the arguments are passed directly to the command, and you're creating a non-admin user, the command would still ask if the user should be an admin.

Tests for MakeUserCommand

---

resources/lang/en/navigation.php
src/CachetDashboardServiceProvider.php
src/Filament/Pages/EditProfile.php

Closes #275
It's now possible to edit your user's profile. We can extend this in the future as more options are added.

Add Edit Profile page

---

resources/views/components/incident-timeline.blade.php

This PR fixes the issue with reversed date order for past incidents on the Past Incidents section of the site. 
It ensures that the start date appears first, followed by the end date.
- Updated date order in `resources/views/components/incident-timeline.blade.php`.
Closes #237

Fix date order for past incidents in history (#237)

---

database/migrations/2025_05_11_141054_add_external_dependencies_setting.php
resources/lang/en/settings.php
src/CachetDashboardServiceProvider.php
src/Filament/Pages/Settings/ManageCachet.php
src/Settings/AppSettings.php

Closes #267 
- Switzer will no longer be used in the dashboard when external assets are disabled.
- Grouped some similar view settings together.
- To configure avatars, you will need to manually change the `User` model.

Allow configuring whether to use external dependencies

---

database/migrations/2025_09_13_124815_add_show_when_empty_column_to_metrics_table.php
resources/lang/en/metric.php
src/Filament/Resources/Metrics/MetricResource.php
src/Models/Metric.php
src/View/Components/Metrics.php

Metrics previously needed to have data before they would be shown. We now offer an option to show the metric even when it is empty (has no data).

Add option to show metrics even when empty

---

src/Data/Cachet/ThemeData.php

Since upgrading to Tailwind 4, we weren't correctly providing foreground colors (including some background colors) in the right format.

Fix themes not applying foreground colors
