cachethq/core

- database/factories/IncidentUpdateFactory.php
- database/migrations/2023_08_30_212242_make_incident_updates_columns_nullable.php
- src/Actions/Incident/DeleteIncident.php
- src/Actions/Incident/UpdateIncident.php
- src/Http/Controllers/Api/IncidentController.php
- src/Http/Requests/CreateIncidentRequest.php
- src/Http/Requests/UpdateIncidentRequest.php
- src/Http/Resources/Incident.php
- tests/Feature/Api/IncidentTest.php
- tests/Unit/Actions/Incident/DeleteIncidentTest.php
> Incident API

- routes/api.php
- src/Http/Controllers/Api/GeneralController.php
- tests/Feature/Api/GeneralTest.php
These aren't quite finished yet, as we have no way to:
- Fetch the system status / message
- We haven't built in version checking
I see this more as just laying the groundwork for the future.
> Add general API routes

- database/factories/SubscriberFactory.php
- database/factories/SubscriptionFactory.php
- src/Actions/Component/DeleteComponent.php
- src/Actions/Subscriber/CreateSubscriber.php
- src/Actions/Subscriber/UnsubscribeSubscriber.php
- src/Actions/Subscriber/UpdateSubscriber.php
- src/Events/Subscribers/SubscriberCreated.php
- src/Events/Subscribers/SubscriberUnsubscribed.php
- src/Events/Subscribers/SubscriberVerified.php
- src/Models/Component.php
- src/Models/Subscriber.php
- src/Models/Subscription.php
- tests/Unit/Actions/Component/DeleteComponentTest.php
- tests/Unit/Actions/Subscriber/CreateSubscriberTest.php
- tests/Unit/Actions/Subscriber/UnsubscribeSubscriberTest.php
- tests/Unit/Actions/Subscriber/UpdateSubscriberTest.php
- tests/Unit/Models/SubscriberTest.php
Introduce the *core* backend code of the Subscribers feature, including:
- Actions to subscribe, unsubscribe and update.
- Events get fired.
- Improved relationships and implementation from 2.x.
This PR **does not** include any sending of emails / notifiables. We'll tackle this later on, when we've got further down the line.
**To-do:**
> Subscribers

- composer.json
- testbench.yaml
- workbench/config/query-builder.php
- workbench/routes/api.php
- workbench/routes/console.php
- workbench/routes/web.php
> Test Improvements

- resources/svg/chevron-right.svg
- resources/views/components/cachet.blade.php
- resources/views/setup/index.blade.php
Part of https://github.com/cachethq/core/issues/23
> Implement setup page design

- src/Filament/Resources/ComponentResource/RelationManagers/ComponentsRelationManager.php
That was way easier than I anticipated...
https://github.com/user-attachments/assets/2dd3ca86-dc76-4f80-8086-05ff83f8f366
Closes https://github.com/cachethq/core/issues/86
> Make components orderable within component groups

- resources/views/components/incident.blade.php
Incident display on mobile #88
> Incident display on mobile

- .github/workflows/run-tests.yml
- composer.json
- database/migrations/2015_06_10_122216_AlterTableComponentsDropUserIdColumn.php
- database/migrations/2015_06_10_122229_AlterTableIncidentsDropUserIdColumn.php
- database/migrations/2016_04_05_142933_create_sessions_table.php
- database/migrations/2016_06_05_091615_create_cache_table.php
- workbench/database/migrations/2015_05_24_210939_create_jobs_table.php
This PR allows Cachet to be installed in Laravel 11 apps.
> Upgrade to Laravel 11.x

- resources/views/components/incident-timeline.blade.php
Start page:
When page can be forwared:
> Add today link to timeline template #69

- src/Filament/Resources/ComponentGroupResource.php
- src/Filament/Resources/ComponentResource.php
- src/Filament/Resources/ComponentResource/RelationManagers/ComponentsRelationManager.php
- src/Filament/Resources/IncidentResource.php
- src/Filament/Resources/IncidentResource/RelationManagers/ComponentsRelationManager.php
- src/Filament/Resources/IncidentResource/RelationManagers/IncidentUpdatesRelationManager.php
- src/Filament/Resources/IncidentTemplateResource.php
- src/Filament/Resources/MetricResource.php
- src/Filament/Resources/ScheduleResource.php
- src/Filament/Resources/SubscriberResource.php
- src/Filament/Widgets/Overview.php
Add explicit translatable labels to forms and tables.
> feat: add localization to forms and tables

- resources/views/components/incident-timeline.blade.php
Add date selector on incident timeline #99
Preview
> Add date selector on incident timeline #99

- resources/views/components/header.blade.php
https://laravel.com/docs/11.x/filesystem#file-urls
> Fix public logo URL

- resources/views/components/about.blade.php
- resources/views/components/cachet.blade.php
- src/View/Components/About.php
- src/View/Components/Cachet.php
These changes allow you to use the name and description we have in the application settings both in the meta tag and in the about section improving customization.
> Improving site identity management

- src/CachetCoreServiceProvider.php
- src/Commands/MakeUserCommand.php
- src/Concerns/User.php
Closes https://github.com/cachethq/cachet/issues/4439
> Add a `cachet:make:user` command

- README.md
The README sponsor URL was incorrect.
> Update README.md incorrect sponsor URL

- README.md
> Changing cachet media color dark to light

- resources/views/components/component-group.blade.php
I made a typo here on the translation string
> fix: typo in translation string

- .github/workflows/run-tests.yml
This should help catch other issues such as #173.
> Test on Postgres 14 and 15

- src/Cachet.php
This will make Cachet run normally on Windows.
> Should trim both "/" and "\\"

- src/Filament/Resources/ScheduleResource.php
We needed to adjust how we calculate incomplete schedules.
Closes #190
> Fix schedule badge

- src/Filament/Resources/IncidentResource.php
Hopefully this fixes this issue!
Fixes #193
> Fix calculation of incident badge

- src/Http/Controllers/Api/ComponentController.php
- src/Http/Controllers/Api/ComponentGroupController.php
- src/Http/Controllers/Api/IncidentController.php
- src/Http/Controllers/Api/IncidentUpdateController.php
- src/Http/Controllers/Api/MetricController.php
- src/Http/Controllers/Api/MetricPointController.php
- src/Http/Controllers/Api/ScheduleController.php
- src/Http/Controllers/Api/ScheduleUpdateController.php
Fixes https://github.com/cachethq/core/issues/238
> Fix a bug where the API returns the wrong resource

- src/Http/Controllers/StatusPage/StatusPageController.php
This is when @joelbutcher reminds me we should be using a repository or something...
> Fix the ordering of updates on the incident page

- resources/lang/fr/api_key.php
- resources/lang/fr/cachet.php
- resources/lang/fr/component.php
- resources/lang/fr/component_group.php
- resources/lang/fr/incident.php
- resources/lang/fr/incident_template.php
- resources/lang/fr/integrations.php
- resources/lang/fr/metric.php
- resources/lang/fr/navigation.php
- resources/lang/fr/resource.php
- resources/lang/fr/schedule.php
- resources/lang/fr/settings.php
- resources/lang/fr/subscriber.php
- resources/lang/fr/system_status.php
- resources/lang/fr/user.php
- resources/lang/fr/webhook.php
> Add fr translation 

- resources/lang/fr/cachet.php
- resources/lang/fr/metric.php
Add some missing french translations
> Complete french translations

- composer.json
Bump minor larastan version to fix phpstan failing on lower versions
> Bump minor larastan version
